import { MessageSecurityLevel } from "../MessageInput";
import { MessageType } from "./types";

/**
 * 研讨会话列表模拟数据
 */
export const discussionListData = [
  {
    id: 1,
    name: "张小明",
    avatar: "/images/users/roberta-casas.png",
    lastMessage: "正在输入...",
    time: "18:05",
    unread: 0,
    status: "online",
    isTyping: true,
    category: "recent",
    members: 5,
    tag: "团队",
    securityLevel: "非密" as MessageSecurityLevel,
  },
  {
    id: 2,
    name: "李华",
    avatar: "/images/users/leslie-livingston.png",
    lastMessage: "好的，我们可以做到！",
    time: "14:23",
    unread: 0,
    status: "online",
    category: "recent",
    members: 2,
    tag: "私聊",
    securityLevel: "秘密" as MessageSecurityLevel,
  },
  {
    id: 3,
    name: "王强",
    avatar: "/images/users/neil-sims.png",
    lastMessage: "语音消息",
    time: "10:02",
    unread: 4,
    status: "offline",
    isVoiceMessage: true,
    category: "recent",
    members: 3,
    tag: "项目",
    securityLevel: "机密" as MessageSecurityLevel,
  },
  {
    id: 4,
    name: "赵敏",
    avatar: "/images/users/michael-gough.png",
    lastMessage: "没关系，我会从车站取回物品并带回办公室。",
    time: "07:45",
    unread: 0,
    status: "online",
    category: "recent",
    members: 0,
    tag: "",
    securityLevel: "非密" as MessageSecurityLevel,
  },
  {
    id: 5,
    name: "陈静",
    avatar: "/images/users/bonnie-green.png",
    lastMessage: "发送了一张照片",
    time: "15h",
    unread: 0,
    status: "offline",
    isPhoto: true,
    category: "recent",
    members: 0,
    tag: "",
    securityLevel: "秘密" as MessageSecurityLevel,
  },
  {
    id: 6,
    name: "XXX研究室",
    avatar: "/images/users/zuzhi.png",
    lastMessage: "🎉 太棒了，我们走吧！",
    time: "16h",
    unread: 0,
    status: "online",
    isGroup: true,
    category: "recent",
    members: 0,
    tag: "",
    securityLevel: "非密" as MessageSecurityLevel,
  },
  {
    id: 7,
    name: "XXX研究室党支部",
    avatar: "/images/users/dangzhibu.png",
    lastMessage: "是的，我们可以做到！",
    time: "18h",
    unread: 0,
    status: "offline",
    isGroup: true,
    category: "recent",
    members: 0,
    tag: "",
    securityLevel: "机密" as MessageSecurityLevel,
  },
  {
    id: 8,
    name: "平台专业建设群",
    avatar: "/images/users/gonghui.png",
    lastMessage: "下周三下午2点召开平台建设方案研讨会",
    time: "1d",
    unread: 2,
    status: "online",
    isGroup: true,
    category: "recent",
    members: 48,
    tag: "专业群",
    securityLevel: "非密" as MessageSecurityLevel,
  },
  {
    id: 9,
    name: "XXX研究室工会",
    avatar: "/images/users/gonghui.png",
    lastMessage: "语音消息",
    time: "2d",
    unread: 0,
    status: "offline",
    isVoiceMessage: true,
    isGroup: true,
    category: "recent",
    members: 0,
    tag: "",
    securityLevel: "秘密" as MessageSecurityLevel,
  },
  {
    id: 10,
    name: "吴鑫",
    avatar: "/images/users/robert-brown.png",
    lastMessage: "好久不见，最近怎么样兄弟？",
    time: "1w",
    unread: 0,
    status: "offline",
    category: "recent",
    members: 0,
    tag: "",
    securityLevel: "非密" as MessageSecurityLevel,
  },
  {
    id: 11,
    name: "项目管理群",
    avatar: "/images/users/joseph-mcfall.png",
    lastMessage: "我们下个月再做吧",
    time: "04.03.2025",
    unread: 0,
    status: "online",
    isGroup: true,
    category: "recent",
    members: 0,
    tag: "",
    securityLevel: "机密" as MessageSecurityLevel,
  },
];

/**
 * 消息列表模拟数据
 */
export const messagesData: MessageType[] = [
  {
    id: 1,
    sender: "李四",
    avatarSrc: "/images/users/jese-leos.png",
    content: "大家好，我们今天讨论API集成的问题",
    time: "10:30",
    status: "已读",
    messageType: "text",
    securityLevel: "非密",
  },
  {
    id: 2,
    sender: "我",
    avatarSrc: "/images/users/michael-gough.png",
    content:
      "API集成部分主要是兼容性问题，我们需要确保新版本与旧系统能够正常通信",
    time: "10:32",
    status: "已读",
    messageType: "text",
    isOwn: true,
    securityLevel: "非密",
  },
  {
    id: 3,
    sender: "张三",
    avatarSrc: "/images/users/bonnie-green.png",
    content: "我已经看了一下协议，需要做一些转换适配",
    time: "10:34",
    status: "已读",
    messageType: "text",
    securityLevel: "秘密",
  },
  {
    id: 4,
    sender: "王五",
    avatarSrc: "/images/users/thomas-lean.png",
    content: "主要是API集成部分出现了兼容性问题",
    time: "10:35",
    status: "已读",
    messageType: "text",
    securityLevel: "非密",
  },
  {
    id: 5,
    sender: "李四",
    avatarSrc: "/images/users/jese-leos.png",
    content: "开发任务",
    time: "10:38",
    status: "已读",
    messageType: "task",
    securityLevel: "机密",
    taskData: {
      title: "完成API兼容性适配",
      description: "针对旧系统的接口协议，开发适配层处理数据格式转换",
      dueDate: "2023-05-25",
      priority: "high",
      status: "in-progress",
      progress: 35,
      assignees: [
        {
          id: 1,
          name: "我",
          avatar: "/images/users/michael-gough.png",
        },
        {
          id: 2,
          name: "张三",
          avatar: "/images/users/bonnie-green.png",
        },
      ],
      tags: ["API", "后端", "兼容性"],
    },
  },
  {
    id: 6,
    sender: "张三",
    avatarSrc: "/images/users/bonnie-green.png",
    content: "项目进度评估投票",
    time: "10:39",
    status: "已读",
    messageType: "vote",
    securityLevel: "非密",
    voteData: {
      title: "使用哪个设计方案？",
      description: "请团队成员投票选择产品原型最终采用的设计方案",
      options: [
        { id: 1, text: "方案一：XXX设计方案", votes: 4 },
        { id: 2, text: "方案二：XXX设计方案", votes: 6 },
        { id: 3, text: "方案三：XXX设计方案", votes: 3 },
        { id: 4, text: "方案四：XXX设计方案", votes: 2 },
      ],
      totalVotes: 15,
      deadline: "2023-05-30 18:00",
      hasVoted: false,
    },
  },
  {
    id: 7,
    sender: "王五",
    avatarSrc: "/images/users/thomas-lean.png",
    content: "../images/kanban/task-1.jpg",
    time: "10:40",
    status: "已读",
    messageType: "image",
    securityLevel: "非密",
  },
  {
    id: 8,
    sender: "我",
    avatarSrc: "/images/users/michael-gough.png",
    content: "我看到问题了，这是版本不匹配导致的",
    time: "10:41",
    status: "已读",
    messageType: "text",
    isOwn: true,
    replyTo: {
      sender: "王五",
      message: "主要是API集成部分出现了兼容性问题",
    },
    securityLevel: "非密",
  },
  {
    id: 9,
    sender: "赵六",
    avatarSrc: "/images/users/joseph-mcfall.png",
    content: "开发活动接龙",
    time: "10:45",
    status: "已读",
    messageType: "relay",
    securityLevel: "非密",
    relayData: {
      id: 101,
      title: "API协议讨论会",
      description: "针对API兼容性问题，组织一次讨论会，请有意愿参加的同事报名",
      createdAt: "2023-05-22 10:45",
      deadline: "2023-05-24 18:00",
      status: "ongoing",
      totalParticipants: 6,
      maxParticipants: 10,
      participants: [
        {
          id: 1,
          name: "张三",
          avatar: "/images/users/bonnie-green.png",
          content: "我可以分享之前的经验",
          time: "2023-05-22 11:30",
        },
        {
          id: 2,
          name: "李四",
          avatar: "/images/users/jese-leos.png",
          content: "我负责记录会议内容",
          time: "2023-05-22 13:45",
        },
        {
          id: 3,
          name: "王五",
          avatar: "/images/users/thomas-lean.png",
          content: "我可以准备演示环境",
          time: "2023-05-22 15:20",
        },
      ],
      tags: ["会议", "API", "讨论"],
    },
  },
  {
    id: 10,
    sender: "我",
    avatarSrc: "/images/users/michael-gough.png",
    content: "我已经修复了API问题，大家可以更新代码测试一下",
    time: "10:48",
    status: "已读",
    messageType: "text",
    isOwn: true,
    reactions: ["👍", "🎉"],
    securityLevel: "非密",
  },
  {
    id: 11,
    sender: "张三",
    avatarSrc: "/images/users/bonnie-green.png",
    content:
      "我这边测试了一下，已经可以正常工作了。不过有个小问题，数据返回时有点慢，可能需要优化一下。",
    time: "10:50",
    status: "已读",
    messageType: "text",
    securityLevel: "非密",
  },
  {
    id: 12,
    sender: "我",
    avatarSrc: "/images/users/michael-gough.png",
    content: "好的，我看一下响应时间的问题",
    time: "10:51",
    status: "已读",
    messageType: "text",
    isOwn: true,
    isEdited: true,
    securityLevel: "非密",
  },
  {
    id: 13,
    sender: "李四",
    avatarSrc: "/images/users/jese-leos.png",
    content: "太好了，我马上测试",
    time: "10:52",
    status: "已读",
    messageType: "text",
    replyTo: {
      sender: "我",
      message: "我已经修复了API问题，大家可以更新代码测试一下",
    },
    securityLevel: "非密",
  },
  {
    id: 14,
    sender: "张三",
    avatarSrc: "/images/users/bonnie-green.png",
    content: "这是我们的项目时间线，请大家查看一下",
    time: "10:56",
    status: "已读",
    messageType: "text",
    replyTo: {
      sender: "张三",
      message: "../images/users/neil-sims.png",
    },
    securityLevel: "非密",
  },
  {
    id: 15,
    sender: "我",
    avatarSrc: "/images/users/michael-gough.png",
    content: "语音消息 (3:42)",
    time: "11:00",
    status: "已读",
    messageType: "voice",
    isOwn: true,
    securityLevel: "非密",
  },
  {
    id: 16,
    sender: "我",
    avatarSrc: "/images/users/michael-gough.png",
    content: "Flowbite Terms & Conditions.pdf",
    time: "11:05",
    status: "已读",
    messageType: "file",
    isOwn: true,
    securityLevel: "非密",
  },
  {
    id: 17,
    sender: "我",
    avatarSrc: "/images/users/michael-gough.png",
    content: "../images/kanban/task-2.jpg",
    time: "11:10",
    status: "已读",
    messageType: "image",
    isOwn: true,
    securityLevel: "非密",
  },
];

/**
 * 平台专业建设群消息列表模拟数据
 */
export const platformGroupMessagesData: MessageType[] = [
  {
    id: 1,
    sender: "系统管理员",
    avatarSrc: "/images/users/jese-leos.png",
    content: "平台专业建设群入群须知",
    time: "2023-05-01 09:00",
    status: "已读",
    messageType: "notice",
    securityLevel: "非密",
    noticeData: {
      title: "平台专业建设群入群须知",
      content:
        "欢迎加入平台专业建设群！本群旨在促进平台技术的交流与研讨，为专业建设提供支持。请遵守以下规则：\n\n1. 请勿发布与平台建设无关的内容\n2. 尊重他人观点，保持友好交流\n3. 技术讨论请提供详细的背景和问题描述\n4. 分享资料时请注明出处\n5. 敏感信息请谨慎发布，遵守保密规定",
      type: "welcome",
      importance: "important",
      requireConfirmation: true,
      confirmedBy: [
        {
          id: 1,
          name: "张小明",
          avatar: "/images/users/roberta-casas.png",
          time: "2023-05-01 09:05",
        },
        {
          id: 2,
          name: "李华",
          avatar: "/images/users/leslie-livingston.png",
          time: "2023-05-01 09:10",
        },
      ],
    },
  },
  {
    id: 2,
    sender: "王教授",
    avatarSrc: "/images/users/joseph-mcfall.png",
    content: "平台建设历史与现状",
    time: "2023-05-02 10:30",
    status: "已读",
    messageType: "knowledge",
    securityLevel: "非密",
    knowledgeData: {
      title: "平台建设历史与现状",
      content:
        "自2010年起，我们开始规划平台建设，经历了三个主要阶段：\n\n第一阶段（2010-2015）：基础设施建设\n主要完成了核心计算环境、存储系统和基础网络的搭建。\n\n第二阶段（2015-2020）：应用体系构建\n完成了业务系统的设计与实现，建立了初步的数据中心。\n\n第三阶段（2020至今）：智能化升级\n引入AI技术，提升平台智能化水平，强化数据分析能力。\n\n目前平台已支撑40余个业务系统，注册用户超过1万人，日均访问量10万次。",
      category: "平台历史",
      tags: ["平台建设", "发展历程", "技术演进"],
      author: "王教授",
      authorAvatar: "/images/users/joseph-mcfall.png",
      createdAt: "2023-05-02 10:30",
      lastUpdated: "2023-05-10 15:45",
      viewCount: 245,
      relatedTopics: ["平台架构设计", "发展规划", "技术选型"],
    },
  },
  {
    id: 3,
    sender: "张工程师",
    avatarSrc: "/images/users/robert-brown.png",
    content: "平台架构设计文档",
    time: "2023-05-03 13:20",
    status: "已读",
    messageType: "document",
    securityLevel: "非密",
    documentData: {
      title: "平台架构设计文档V2.0",
      fileType: "word",
      fileSize: "5.8 MB",
      pageCount: 42,
      lastEditor: "张工程师",
      lastEditorAvatar: "/images/users/robert-brown.png",
      lastEditTime: "2023-05-03 13:15",
      collaborators: [
        {
          id: 1,
          name: "张工程师",
          avatar: "/images/users/robert-brown.png",
          role: "owner",
        },
        {
          id: 2,
          name: "李研究员",
          avatar: "/images/users/thomas-lean.png",
          role: "editor",
        },
        {
          id: 3,
          name: "王教授",
          avatar: "/images/users/joseph-mcfall.png",
          role: "viewer",
        },
      ],
      status: "editing",
      version: "2.0.5",
      commentCount: 18,
    },
  },
  {
    id: 4,
    sender: "李研究员",
    avatarSrc: "/images/users/thomas-lean.png",
    content: "平台技术选型分析",
    time: "2023-05-04 11:15",
    status: "已读",
    messageType: "knowledge",
    securityLevel: "非密",
    knowledgeData: {
      title: "平台技术选型分析",
      content:
        "基于业务需求和技术发展趋势，我们对平台关键技术进行了选型分析：\n\n1. **计算框架**：采用微服务架构，使用Spring Cloud生态\n2. **数据存储**：关系型数据库使用PostgreSQL，非关系型使用MongoDB\n3. **消息队列**：采用Kafka，支撑高并发场景\n4. **搜索引擎**：使用Elasticsearch，提供高效搜索能力\n5. **容器化**：采用Docker+Kubernetes架构\n6. **前端框架**：使用React+TypeScript，支持组件化开发\n\n技术选型考虑了性能、安全性、扩展性和社区活跃度等因素，同时兼顾了团队的技术积累。",
      category: "技术架构",
      tags: ["技术选型", "架构设计", "微服务"],
      author: "李研究员",
      authorAvatar: "/images/users/thomas-lean.png",
      createdAt: "2023-05-04 11:15",
      lastUpdated: "2023-05-12 09:30",
      viewCount: 178,
      attachments: [
        {
          id: 1,
          name: "技术选型评估表.xlsx",
          type: "excel",
          size: "1.2 MB",
        },
      ],
      relatedTopics: ["微服务架构", "容器化部署", "前端技术栈"],
    },
  },
  {
    id: 5,
    sender: "系统管理员",
    avatarSrc: "/images/users/system-admin.png",
    content: "平台建设方案研讨会通知",
    time: "2023-05-10 16:00",
    status: "已读",
    messageType: "notice",
    securityLevel: "非密",
    noticeData: {
      title: "平台建设方案研讨会通知",
      content:
        "各位专家和团队成员：\n\n定于下周三（5月17日）下午2点在3号会议室召开平台建设方案研讨会，请各位准时参加。\n\n会议议题：\n1. 平台3.0版本规划讨论\n2. 微服务架构升级方案评审\n3. 数据治理体系建设\n4. 智能化功能规划\n\n请相关模块负责人提前准备材料，会议预计持续3小时。",
      type: "event",
      importance: "important",
      expireDate: "2023-05-17 14:00",
      attachments: [
        {
          id: 1,
          name: "会议议程.pdf",
          type: "pdf",
          size: "0.5 MB",
        },
      ],
    },
  },
  {
    id: 6,
    sender: "赵架构师",
    avatarSrc: "/images/users/architect.png",
    content: "微服务架构升级方案",
    time: "2023-05-12 10:45",
    status: "已读",
    messageType: "document",
    securityLevel: "非密",
    documentData: {
      title: "微服务架构升级方案V1.2",
      fileType: "pdf",
      fileSize: "8.3 MB",
      pageCount: 36,
      lastEditor: "赵架构师",
      lastEditorAvatar: "/images/users/architect.png",
      lastEditTime: "2023-05-12 10:30",
      collaborators: [
        {
          id: 1,
          name: "赵架构师",
          avatar: "/images/users/architect.png",
          role: "owner",
        },
        {
          id: 2,
          name: "张工程师",
          avatar: "/images/users/engineer.png",
          role: "editor",
        },
        {
          id: 3,
          name: "李研究员",
          avatar: "/images/users/researcher.png",
          role: "editor",
        },
      ],
      status: "viewing",
      version: "1.2.3",
      commentCount: 23,
    },
  },
  {
    id: 7,
    sender: "我",
    avatarSrc: "/images/users/michael-gough.png",
    content: "关于微服务拆分的建议",
    time: "2023-05-13 14:20",
    status: "已读",
    messageType: "text",
    isOwn: true,
    securityLevel: "非密",
    reactions: ["👍", "💡"],
  },
  {
    id: 8,
    sender: "钱测试",
    avatarSrc: "/images/users/tester.png",
    content: "平台性能测试报告",
    time: "2023-05-14 09:30",
    status: "已读",
    messageType: "knowledge",
    securityLevel: "非密",
    knowledgeData: {
      title: "平台性能测试报告",
      content:
        "针对平台2.5版本进行了全面性能测试，主要结果如下：\n\n1. **并发用户数**：系统可稳定支持2000并发用户\n2. **响应时间**：平均响应时间280ms，95%请求响应时间不超过500ms\n3. **吞吐量**：系统峰值吞吐量达到3500 TPS\n4. **资源利用率**：CPU平均利用率65%，内存利用率70%\n\n性能瓶颈主要在数据库层面，建议对热点查询进行优化，并加强缓存策略。此外，部分API响应时间较长，需要进行代码级优化。",
      category: "性能测试",
      tags: ["性能测试", "压力测试", "瓶颈分析"],
      author: "钱测试",
      authorAvatar: "/images/users/tester.png",
      createdAt: "2023-05-14 09:30",
      lastUpdated: "2023-05-14 15:45",
      viewCount: 124,
      attachments: [
        {
          id: 1,
          name: "性能测试详细报告.pdf",
          type: "pdf",
          size: "4.7 MB",
        },
        {
          id: 2,
          name: "测试数据集.zip",
          type: "archive",
          size: "12.5 MB",
        },
      ],
      relatedTopics: ["性能优化", "数据库调优", "缓存策略"],
    },
  },
  {
    id: 9,
    sender: "孙产品",
    avatarSrc: "/images/users/bonnie-green.png",
    content: "平台3.0版本需求规格说明",
    time: "2023-05-15 13:10",
    status: "已读",
    messageType: "document",
    securityLevel: "非密",
    documentData: {
      title: "平台3.0版本需求规格说明书",
      fileType: "word",
      fileSize: "7.2 MB",
      pageCount: 58,
      lastEditor: "孙产品",
      lastEditorAvatar: "/images/users/bonnie-green.png",
      lastEditTime: "2023-05-15 13:00",
      collaborators: [
        {
          id: 1,
          name: "孙产品",
          avatar: "/images/users/bonnie-green.png",
          role: "owner",
        },
        {
          id: 2,
          name: "王教授",
          avatar: "/images/users/joseph-mcfall.png",
          role: "editor",
        },
        {
          id: 3,
          name: "赵架构师",
          avatar: "/images/users/lana-byrd.png",
          role: "editor",
        },
      ],
      status: "editing",
      version: "0.9.1",
      commentCount: 32,
    },
  },
  {
    id: 10,
    sender: "周安全",
    avatarSrc: "/images/users/helene-engels.png",
    content: "平台安全架构设计指南",
    time: "2023-05-16 11:25",
    status: "已读",
    messageType: "knowledge",
    securityLevel: "非密",
    knowledgeData: {
      title: "平台安全架构设计指南",
      content:
        "为确保平台安全，提供以下架构设计指南：\n\n1. **边界安全**：采用多层防护，包括防火墙、WAF和API网关\n2. **身份认证**：实现基于OAuth2.0和OIDC的统一认证\n3. **权限控制**：采用RBAC模型，细粒度控制资源访问\n4. **数据安全**：敏感数据加密存储，传输采用TLS1.3\n5. **审计日志**：全面记录用户操作，支持安全事件追溯\n6. **漏洞管理**：建立漏洞扫描和修复流程\n\n所有新增组件必须通过安全评审，确保符合平台安全标准。",
      category: "安全架构",
      tags: ["安全设计", "认证授权", "数据加密"],
      author: "周安全",
      authorAvatar: "/images/users/helene-engels.png",
      createdAt: "2023-05-16 11:25",
      lastUpdated: "2023-05-16 16:40",
      viewCount: 96,
      attachments: [
        {
          id: 1,
          name: "安全漏洞检查清单.pdf",
          type: "pdf",
          size: "1.8 MB",
        },
      ],
      relatedTopics: ["零信任架构", "安全合规", "应急响应"],
    },
  },
  {
    id: 11,
    sender: "王教授",
    avatarSrc: "/images/users/michael-gough.png",
    content: "有什么需要我帮忙的地方吗？",
    time: "昨天 14:26",
    status: "已读",
    messageType: "text",
    isOwn: false,
    isEdited: false,
    securityLevel: "非密",
  },
  {
    id: 12,
    sender: "系统通知",
    avatarSrc: "/images/users/zuzhi.png",
    content: "",
    time: "昨天 15:05",
    status: "已读",
    messageType: "notice",
    isOwn: false,
    isEdited: false,
    securityLevel: "非密",
    noticeData: {
      title: "平台专业建设群 - 群规则更新",
      content:
        "各位成员请注意，群规则已更新：\n\n1. 本群用于讨论平台建设相关专业技术问题\n2. 请勿发布与主题无关的内容\n3. 重要文档和知识将固定在群置顶区\n4. 技术讨论请尽量提供详细信息和上下文\n5. 群内分享的资料仅限群内成员使用\n6. 每周五下午3点为技术分享时间",
      type: "rules",
      importance: "important",
      expireDate: "2023-12-31",
      requireConfirmation: true,
      confirmedBy: [
        {
          id: 1,
          name: "张主任",
          avatar: "/images/users/robert-brown.png",
          time: "2023-09-15 15:30",
        },
        {
          id: 2,
          name: "李工程师",
          avatar: "/images/users/neil-sims.png",
          time: "2023-09-15 15:45",
        },
        {
          id: 3,
          name: "王教授",
          avatar: "/images/users/michael-gough.png",
          time: "2023-09-15 16:20",
        },
        {
          id: 4,
          name: "赵研究员",
          avatar: "/images/users/thomas-lean.png",
          time: "2023-09-16 09:15",
        },
        {
          id: 5,
          name: "刘设计师",
          avatar: "/images/users/jese-leos.png",
          time: "2023-09-16 10:30",
        },
        {
          id: 6,
          name: "孙博士",
          avatar: "/images/users/bonnie-green.png",
          time: "2023-09-16 14:20",
        },
        {
          id: 7,
          name: "吴经理",
          avatar: "/images/users/roberta-casas.png",
          time: "2023-09-16 15:45",
        },
      ],
    },
  },
  {
    id: 13,
    sender: "党支部",
    avatarSrc: "/images/users/dangzhibu.png",
    content: "",
    time: "今天 09:10",
    status: "已读",
    messageType: "notice",
    isOwn: false,
    isEdited: false,
    securityLevel: "非密",
    noticeData: {
      title: "关于加强技术创新的通知",
      content:
        "为促进技术创新和知识共享，现通知如下：\n\n1. 鼓励各单位开展技术创新活动\n2. 建立健全知识管理与分享机制\n3. 提升核心技术自主研发能力\n4. 加强技术人才培养与引进",
      type: "announcement",
      importance: "normal",
      expireDate: "2023-12-31",
      attachments: [
        {
          id: 1,
          name: "技术创新方案.docx",
          type: "Word文档",
          size: "156 KB",
        },
      ],
    },
  },
  {
    id: 14,
    sender: "工会",
    avatarSrc: "/images/users/gonghui.png",
    content: "",
    time: "今天 10:25",
    status: "已读",
    messageType: "notice",
    isOwn: false,
    isEdited: false,
    securityLevel: "非密",
    noticeData: {
      title: "关于开展团建活动的通知",
      content:
        "为增强团队凝聚力，工会决定于10月15日组织秋季团建活动，请各部门做好相关准备工作。具体安排如下：\n\n活动时间：10月15日（周六）上午9:00-下午17:00\n活动地点：市郊森林公园\n活动内容：户外拓展、烧烤、游戏等",
      type: "event",
      importance: "normal",
      expireDate: "2023-10-10",
      requireConfirmation: true,
      confirmedBy: [
        {
          id: 1,
          name: "张主席",
          avatar: "/images/users/bonnie-green.png",
          time: "2023-09-15 15:30",
        },
        {
          id: 2,
          name: "李委员",
          avatar: "/images/users/joseph-mcfall.png",
          time: "2023-09-15 15:45",
        },
        {
          id: 3,
          name: "赵会员",
          avatar: "/images/users/leslie-livingston.png",
          time: "2023-09-15 16:20",
        },
        {
          id: 4,
          name: "刘会员",
          avatar: "/images/users/roberta-casas.png",
          time: "2023-09-16 09:15",
        },
        {
          id: 5,
          name: "刘会员",
          avatar: "/images/users/bonnie-green.png",
          time: "2023-09-16 10:30",
        },
      ],
    },
  },
  {
    id: 15,
    sender: "李工程师",
    avatarSrc: "/images/users/neil-sims.png",
    content: "",
    time: "今天 11:15",
    status: "已读",
    messageType: "knowledge",
    isOwn: false,
    isEdited: false,
    securityLevel: "非密",
    knowledgeData: {
      title: "平台API接口设计规范",
      content:
        "API接口设计应遵循RESTful架构风格，具体要求如下：\n1. 使用HTTP动词表示操作类型（GET, POST, PUT, DELETE）\n2. 使用名词复数形式表示资源集合\n3. 版本信息应包含在URL中\n4. 使用HTTP状态码表示请求结果\n5. 支持分页、过滤、排序和字段选择\n6. 提供详细的错误信息",
      category: "技术规范",
      tags: ["API", "RESTful", "接口设计", "开发规范"],
      author: "李工程师",
      authorAvatar: "/images/users/neil-sims.png",
      createdAt: "2023-09-18 11:15",
      lastUpdated: "2023-09-18 11:15",
      viewCount: 23,
      attachments: [
        {
          id: 1,
          name: "API接口设计规范完整版.pdf",
          type: "PDF文档",
          size: "2.3 MB",
        },
      ],
      relatedTopics: ["微服务架构", "前后端分离", "接口文档"],
    },
  },
  {
    id: 16,
    sender: "刘设计师",
    avatarSrc: "/images/users/jese-leos.png",
    content: "",
    time: "今天 11:30",
    status: "已读",
    messageType: "document",
    isOwn: false,
    isEdited: false,
    securityLevel: "非密",
    documentData: {
      title: "平台UI组件设计规范.docx",
      fileType: "word",
      fileSize: "3.5 MB",
      pageCount: 28,
      lastEditor: "刘设计师",
      lastEditorAvatar: "/images/users/jese-leos.png",
      lastEditTime: "今天 11:30",
      collaborators: [
        {
          id: 1,
          name: "李工程师",
          avatar: "/images/users/neil-sims.png",
          role: "editor",
        },
        {
          id: 2,
          name: "张主任",
          avatar: "/images/users/robert-brown.png",
          role: "viewer",
        },
        {
          id: 3,
          name: "王教授",
          avatar: "/images/users/michael-gough.png",
          role: "viewer",
        },
        {
          id: 4,
          name: "陈架构师",
          avatar: "/images/users/helene-engels.png",
          role: "editor",
        },
      ],
      status: "editing",
      version: "1.3",
      commentCount: 8,
    },
  },
];

/**
 * 默认话题置顶数据
 */
export const defaultPinnedTopic = {
  title: "API集成兼容性问题讨论",
  content:
    "讨论如何解决当前版本与旧系统协议的兼容性问题，确保数据正确传输和处理",
  creator: "李四",
  createdAt: "2023-05-20",
  isPinned: true,
  messageId: 1,
};
